### ISSUE TITLE
Add support for creating views in schemas other than `public`

### ISSUE THREAD

**Issue by devonestes** [thoughtbot/scenic#125]
We're starting to use Scenic in production at my company, and I needed to create a view in our database that was in a schema other than `public`. Specifically, we use schemas to segregate data by year, so we have tables like `fy2014.schools`, `fy2015.schools` and `fy2016.schools`.

The generator did a pretty good job, but I submitted a PR that would add more fluent support for this functionality in #124. Not sure if you want to actually include this feature or not, but I figured it couldn't hurt, and I'll probably use my patched version of the gem anyway unless these are merged into master, so I figured I'd submit it in case you wanted to go that direction.

**Comment by devonestes** [comment]
Sorry - guess this is a duplication of #95.

**Comment by derekprior** [comment]
I would like to include this feature, presuming it can be done relatively cleanly. Closing in favor of the PR though.
