### ISSUE TITLE
Difficulty in seeing differences between versions - different way to handle that?

### ISSUE THREAD

**Issue by devonestes** [thoughtbot/scenic#132]
We're using Scenic in production now, and one of my co-workers brought up what might be a good point. We made a change to a view, and when he was reviewing the code on Github you can only see that a new file was created and you don't get a sense of what has changed between version 1 and version 2. He just diff'd the two versions to see what had changed, but having to leave Github to see a diff of the versions while reviewing code is sub-optimal.

I can't for the life of me think of a way to avoid this, but I wanted to mention it in case someone did have a brilliant idea about this since I think it would remove a non-trivial source of friction from the user experience.

**Comment by derekprior** [comment]
The schema diff should appear in reasonably, albeit not perfect, format in `schema.rb` or `structure.rb`.

**Comment by devonestes** [comment]
That's a really great way to handle it - we'll just look there!
