### ISSUE TITLE
Materialized Concurrent views

### ISSUE THREAD

**Issue by krainboltgreene** [thoughtbot/scenic#133]
If you create a materialized view, and then refresh that view concurrently, using the scenic public APIs, you'll get this error:

``` 
ERROR:  materialized view "v2_activities" has not been populated
```

**Comment by derekprior** [comment]
I'm not able to reproduce this. I did the following:

1. Ran `rails generate scenic:view test --materialized`
2. Edited `tests_v01.sql` to be `select email from users;`
3. Edited the migrationg to add `add_index :tests, :email, unique: true`
4. Ran `rake db:migrate`
5. Ran `select * from tests` in the psql console. It had data.
6. Ran `Scenic.database.refresh_materialized_view(:tests, concurrently: true)`. This succeeded.

What am I missing?

**Comment by krainboltgreene** [comment]
Hmm. So possibly two things: one the selected table needs to have no
records and the view has to (obviously) have no records. This is when it
happens, during request specs.

**Comment by derekprior** [comment]
I'm completely unable to reproduce this. I've only ever seen this issue when *selecting* from a materialized view that was created with the `WITH NO DATA` command (which Scenic does not currently support). In those cases, the fix is to run the refresh (and indeed that's what the full message usually hints at).

Would it be possible for you to post your `schema.rb` file (I'd suggest upgrading to 1.2 and running `rake db:schema:dump` since we improved schema dumps just yesterday)? If you're not able to do that, would you be able to take a crack at a minimal reproduction

**Comment by krainboltgreene** [comment]
We ended up moving away from a materialized view, but I'll see if I can!

On Sat, Feb 6, 2016 at 11:55 AM, Derek Prior <notifications@github.com>
wrote:

> I'm completely unable to reproduce this. I've only ever seen this issue
> when *selecting* from a materialized view that was created with the WITH
> NO DATA command (which Scenic does not currently support). In those
> cases, the fix is to run the refresh (and indeed that's what the full
> message usually hints at).
>
> Would it be possible for you to post your schema.rb file (I'd suggest
> upgrading to 1.2 and running rake db:schema:dump since we improved schema
> dumps just yesterday)? If you're not able to do that, would you be able to
> take a crack at a minimal reproduction
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/scenic/issues/133#issuecomment-180847041>.
>



-- 
Kurtis Rainbolt-Greene, Software Developer
Founder of Difference Engineers

2985 San Marino St.
Los Angeles, CA 90006
202-643-2263

**Comment by aaronromeo** [comment]
I ran into this issue in my test environment. I have a test database which is seeded with test data and I'm using concurrent materialized views (my refresh command on my view model looks like the following).

```
  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: true, cascade: false)
  end
```

I was able to get around this by adding the following code to the `spec_helper.rb`.
```
ActiveRecord::Base.connection.execute("REFRESH MATERIALIZED VIEW view_name;")
```
(where `view_name` is the name of my view).
