### ISSUE TITLE
Views from postgis getting including in schema.rb

### ISSUE THREAD

**Issue by soul2197** [thoughtbot/scenic#134]
When using this gem with postgis, it adds the following views to schema.rb: `geography_columns`, `geometry_columns`, `raster_columns`, `raster_overviews`. This causes problems when running the tests because they try to create these views but they already exist.

Not sure what the best course of action is here but as a temporary work around I am going to try forking the repo and explicitly blacklisting those views to see if it fixes my problem. Please let me know if there is a better solution!

**Comment by derekprior** [comment]
Here's where we get the views from postgres: https://github.com/thoughtbot/scenic/blob/master/lib/scenic/adapters/postgres/views.rb#L25

Here's where we ignore certain tables from rails and other things the adapter (I think) tells us to ignore:
https://github.com/thoughtbot/scenic/blob/master/lib/scenic/schema_dumper.rb#L12

My hope would be that there's enough information in the postgres catalog or that the postgis adapter can provide that we'd be able to programmatically filter those views without resorting to a blacklist. I don't have anything where I'm using postgis so I don't have a test readily available. It'll take me a bit to dig into this.

**Comment by derekprior** [comment]
Oh, and here's a non-forking workaround for this issue (I have not tested, but I think it should work):

```ruby
# config/initializers/schema_dumper.rb

ActiveRecord::SchemaDumper.ignore_tables += [<the postgis views>]
```

But I'd still welcome help trying to figure out how to handle this automatically.

**Comment by soul2197** [comment]
When looking at the list of views I did not notice anything that stood out. The only difference I could see between those ones and the ones we had added ourselves in a migration was that the postgis ones had a value populated in the `relacl` column and the ones we created had NULL there but I don't know what that column means or is used for. 

I tried the forking solution and it worked (https://github.com/soul2197/scenic/commit/a35cca27030ee66c7861bed2c4c45d9395af775a) but I will try the non-forking one as well so I can stay on the latest version easier.

**Comment by soul2197** [comment]
The non-forking working around you provided works perfectly. Thanks for the quick response!

**Comment by derekprior** [comment]
@soul2197 Are you using the PostGIS adapter gem for rails? It does seem to set some `ignore_tables`. Perhaps it's missing a few?

https://github.com/rgeo/activerecord-postgis-adapter/blob/d0d47db10f22525928c2d62b8c244d09137bbec2/lib/active_record/connection_adapters/postgis/setup.rb#L5

**Comment by derekprior** [comment]
I've opened https://github.com/rgeo/activerecord-postgis-adapter/issues/208 as a fix with the PostGIS adapter. I think that's the proper place for it to be addressed.
