### ISSUE TITLE
Cannot migrate to a materialized view from a normal view

### ISSUE THREAD

**Issue by adamnbowen** [thoughtbot/scenic#138]
It seems that there isn't an easy way to migrate from a normal database view to a materialized view.  Since `update_view` generates a `DROP MATERIALIZED VIEW view_name` statement whenever `:materialized` is true, it will fail when `view_name` is a non-materialized view.

So if we'd like to support a way for users to migrate from a normal view to a materialized one, we'll either need to provide a second type of migration generation command or we'll need to add some logic into the existing one, checking for whether the view already exists as a non-materialized view.

You can see my demo repo where the issue exists here: https://github.com/adamnbowen/test-scenic/tree/materialized-migration.  That repo is on Rails 5, but I don't see how the issue would be Rails 5 specific.

Note that in my test repo, you'll need to inject environment variables for your database username, password and port—you can see the config in config/database.yml for the appropriate variables to set.

The commands I ran to generate the migrations were `rails g scenic:model ActiveUser` and then `rails g scenic:model ActiveUser --materialized`, where a `rake db:migrate` on the first migration worked just fine, and the failure only happened after the second migration.

```
$ rails db:migrate
== 20160206232756 UpdateActiveUsersToVersion2: migrating ======================
-- update_view(:active_users, {:version=>2, :revert_to_version=>1, :materialized=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::WrongObjectType: ERROR:  "active_users" is not a materialized view
HINT:  Use DROP VIEW to remove a view.
: DROP MATERIALIZED VIEW "active_users";/Users/adambowen/src/test-scenic/db/migrate/20160206232756_update_active_users_to_version_2.rb:3:in `change'
/Users/adambowen/src/test-scenic/bin/rails:9:in `require'
/Users/adambowen/src/test-scenic/bin/rails:9:in `<top (required)>'
/Users/adambowen/src/test-scenic/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
ActiveRecord::StatementInvalid: PG::WrongObjectType: ERROR:  "active_users" is not a materialized view
HINT:  Use DROP VIEW to remove a view.
: DROP MATERIALIZED VIEW "active_users";
/Users/adambowen/src/test-scenic/db/migrate/20160206232756_update_active_users_to_version_2.rb:3:in `change'
/Users/adambowen/src/test-scenic/bin/rails:9:in `require'
/Users/adambowen/src/test-scenic/bin/rails:9:in `<top (required)>'
/Users/adambowen/src/test-scenic/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
PG::WrongObjectType: ERROR:  "active_users" is not a materialized view
HINT:  Use DROP VIEW to remove a view.
/Users/adambowen/src/test-scenic/db/migrate/20160206232756_update_active_users_to_version_2.rb:3:in `change'
/Users/adambowen/src/test-scenic/bin/rails:9:in `require'
/Users/adambowen/src/test-scenic/bin/rails:9:in `<top (required)>'
/Users/adambowen/src/test-scenic/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by derekprior** [comment]
Thanks for taking the time to submit such a detailed report. You can migrate to a materialized view by:

```
drop_view :foo
create_view :foo, version: 2, materialized: true
```

You would have to write up and down in your migration for this. This is by design because I don't think this warrants a special reversible schema statement and generator flag.

**Comment by derekprior** [comment]
I would like to investigate the feasibility of catching this error and logging a helpful and instructive message. I think that could go a long way to preventing confusion. 

I think we would have to catch errors caused by non-existent views in drop_view and check if the named view exists as the other type. If it does, we log a message similar to my message above.

**Comment by adamnbowen** [comment]
I think that makes sense—It's an uncommon enough problem that it probably doesn't warrant a special type of migration, but providing the error message would at least prevent someone from filing a new issue like I did today ;).

I am having some difficulty getting the `down` migration written correctly—I'll post in a bit if I'm able to get it working correctly or not.

**Comment by adamnbowen** [comment]
Okay, no, nevermind on the down migration: my latest commit in the brand gets things solved—I ended up with:

```ruby
  def up
    drop_view :active_users
    create_view :active_users,
      version: 2,
      materialized: true
  end

  def down
    drop_view :active_users, materialized: true
    create_view :active_users, version: 1
  end
```

**Comment by sirwolfgang** [comment]
This seems like it would be a common flow, can we add a bit explaining the transition in the readme/docs?

**Comment by calebthompson** [comment]
We'd be open to a README PR for sure. It seems like this specific issue has been resolved but follow-ups for documenting or handling the error at migration time are welcome.
