### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by GeorgeDewar** [thoughtbot/scenic#146]
This is more of a question than an issue.

I have the some problem with a couple of small functions in PostgreSQL that Scenic is designed to solve for views. Using scenic for my views makes perfect sense, but it's a shame that it doesn't handle functions the same way.

Could you see Scenic extending to things that aren't views (despite the fact that a scenic function or worse, a scenic procedure doesn't sound nearly as cool), or would you see that being a totally separate, somewhat similar project?

**Comment by derekprior** [comment]
I think it'd be great to have support for database functions in rails, but I don't see it as part of Scenic. I prefer libraries that are focused on a single tool. I could envision extracting something out of scenic for the generator/file name lookup stuff that could be used for stuff like this, but I wouldn't be able to guess at what is extractable. I'd have to see actual code.

Right now, there's no time I have myself to write or maintain something for functions, but if you want to tackle it by ripping scenic apart to accommodate it then it's possible we could find some extractable commonalities.

**Comment by GeorgeDewar** [comment]
Thanks @derekprior, that's about what I thought. I'm fairly certain there'd be a common core for things that have to be redefined every time they're changed (functions, procedures, views, etc), though it would be very small (and therefore it may or may not be worth extracting).

I doubt I'll find the time myself either, but you never know...

Thanks again for the quick response.
