### ISSUE TITLE
Tests and "materialized views" - "cannot change materialized view"

### ISSUE THREAD

**Issue by StanBright** [thoughtbot/scenic#149]
Hi,

I'm wondering how you have set your tests up, when you have materialized views in your stack.

After introducing one materialized view with scenic (a very helpful gem), all my tests started failing with:
```
ActiveRecord::StatementInvalid: PG::WrongObjectType: ERROR:  cannot change materialized view "view_name"
: DELETE FROM "view_name"
```

I'm using **Postgres, structure.sql and Rails 4.2.5.2.**

Note, I know this issue isn't related directly to **scenic**. Yet, I believe others using scenic should have it too.

Thanks for any ideas on how to handle this.

**Comment by calebthompson** [comment]
FWIW, I think the behavior of Scenic and structure.sql is undefined when loading the database. All we're doing for you is creating the views.

Can you provide an otherwise simple test that causes the error as well? It looks like at some point something is calling delete_all or similar on the view's AR::B subclass. That could be your test or a test helper such as DatabaseCleaner.

**Comment by StanBright** [comment]
Thanks @calebthompson. I found the culprit. I had some blank fixture files. I think that the default **ActiveSupport::TestCase setup** behaviour is to "delete all" from the tables of all fixtures. Basically, I had to remove the default fixtures generated by **rails generate scenic:model**.

Maybe,  **rails generate scenic:model** should not generate any fixture files?

**Comment by calebthompson** [comment]
Yeah good point. Looks like we hook into the NamedBase generator that likely also includes ActiveSupport::TestCase generation.

**Comment by derekprior** [comment]
I feel like thats correct behavior (hooking into whatever test generation you may have configured). @calebthompson do you suggest we delete a fixture if its generated?

**Comment by calebthompson** [comment]
Not necessarily, but worth discussing. It may be a documentation fix.

**Comment by robertoplancarte** [comment]
I think it is a good idea to document this or at least mention it on the README. Awesome gem btw :)
