### ISSUE TITLE
Generating updates to materialized views

### ISSUE THREAD

**Issue by lperiodbose** [thoughtbot/scenic#154]
When I update a view as so...

```
$ rails generate scenic:view recipient_search_results
      create  db/views/recipient_search_results_v03.sql
      create  db/migrate/20160525194954_update_recipient_search_results_to_version_3.rb
```

...the generated migration doesn't have the `materialized: true` option on it, even though the view being replaced was previously materialized.

When I subsequently...

```
$ rails db:migrate
== 20160525194954 UpdateRecipientSearchResultsToVersion3: migrating ===========
-- update_view(:recipient_search_results, {:version=>3, :revert_to_version=>2})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::WrongObjectType: ERROR:  "recipient_search_results" is not a view
HINT:  Use DROP MATERIALIZED VIEW to remove a materialized view.

```

...this missing option throws an (understandable) error.

Would it be desirable for a generated migration in this instance to have `materialized: true' by default? If so, I'd be happy to take a swing at a PR...

**Comment by magicalbanana** [comment]
Hmm, in my opinion I think it's better that this throws an error because leaving this as a default contradicts the default option that's already used when generating the views. This error also gives you a better understanding of the migrations that relate to the views you have.

**Comment by lperiodbose** [comment]
Maybe there's an opportunity to use documentation to encourage continued use of the `--materialized` flag on update along with create?

**Comment by devonestes** [comment]
Also, maybe the error message in this case could be more descriptive and helpful? The error message that you get by default I can see as kind of confusing... Maybe something along the lines of:

```
ERROR: Tried to update a materialized view with a view.
HINT: Please make sure that `materialized: true` is set in your migration and try again.
```

**Comment by calebthompson** [comment]
I think the current error is pretty clear, but I'd be open to seeing it happen earlier.
