### ISSUE TITLE
Unable to generate schema when running `rake db:drop && rake db:create && rake db:migrate`

### ISSUE THREAD

**Issue by MikeRogers0** [thoughtbot/scenic#159]
I just ran into a bug where if I ran `rake db:drop && rake db:create && rake db:migrate` and my view referenced a table, the command would throw a "table missing" error.

It worked as expected when I initially ran `rake db:drop && rake db:create && rake db:setup`. 

The difference when running the `drop & migrate` query was the `schema.rb` file changed from:

```
ActiveRecord::Schema.define(version: 20160627155534) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "users", force: :cascade do |t|
    # Snip
  end

  create_table "admins", force: :cascade do |t|
    # Snip
  end

  create_view "users_and_admins", <<-SQL
    SELECT * FROM "users"
    UNION ALL 
    SELECT * FROM "admins"
SQL
end
```

to

```
ActiveRecord::Schema.define(version: 20160627155534) do

  create_view "users_and_admins", <<-SQL
    SELECT * FROM "users"
    UNION ALL 
    SELECT * FROM "admins"
SQL

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "users", force: :cascade do |t|
    # Snip
  end

  create_table "admins", force: :cascade do |t|
    # Snip
  end
end
```

I'm think the `create_view` moving to the top of the `schema.rb` file is the cause of the error.  I can provide more information if you need, or if you point me in the right direction I'm happy to attempt to fix.

Setup Information:
Ruby: 2.3.0p0
Rails: 4.2.6
pg: 0.18.4
postgres (PostgreSQL) 9.5.3

**Comment by calebthompson** [comment]
Hmm yes the views should all be added *after* the tables are defined. Looks like a bug in our Rails monkey patch [here](https://github.com/thoughtbot/scenic/blob/master/lib/scenic/schema_dumper.rb#L30-L41) if you want to take a whack at it (I won't have a chance for a bit unfortunately).

**Comment by calebthompson** [comment]
Oh wait that's incorrect. It would be [this](https://github.com/thoughtbot/scenic/blob/master/lib/scenic/schema_dumper.rb#L6-L9), which tells the SchemaDumper to dump tables before views.

**Comment by MikeRogers0** [comment]
I figured out the cause of the problem, it was the (SchemaPlus/schema_validations)[https://github.com/SchemaPlus/schema_validations] gem doing something in the SchemaDumper also.

When I disabled schema_validations, the `rake db:drop && rake db:create && rake db:migrate` commands were able to create the database as expected.

**Comment by calebthompson** [comment]
Good to know, thanks for investigating!
