### ISSUE TITLE
Remove a column

### ISSUE THREAD

**Issue by shivani27** [thoughtbot/scenic#164]
One of my views depends on say x table. When I try to delete "y" column of "x" table it complains that the view uses that column while running migration. I tried doing something similar to this: 
remove_column :posts, :title, :string
update_view :posts_with_aggregate_data, version: 2, revert_to_version: 2

in my migration file, but this doesn't solve the problem. Any help would be appreciated..!! Thanks..!!

**Comment by calebthompson** [comment]
Drop the view, update the table, then re-add the view (possibly a different version if you need to change the select list).

**Comment by shivani27** [comment]
Thanks Caleb..!!Wouldn't that be a bit tricky to track and implement if number of views keep increasing?

**Comment by calebthompson** [comment]
The multiple views version might be, yes. If that's a concern it might make more sense to use a custom table you maintain manually / as a job in your app / etc.
