### ISSUE TITLE
Problem with inflection

### ISSUE THREAD

**Issue by artjomjuferov** [thoughtbot/scenic#165]
If I add inflection, generator does not create migration properly. It pluralizes migration's class name.

ActiveSupport::Inflector.inflections do |inflect|
  inflect.plural /^item$/i, 'item'
end

**Comment by calebthompson** [comment]
What command are you running when generating? With that config, I'm seeing these (expected) results:

```
❯ rails g scenic:view item
      create  db/views/item_v01.sql
      create  db/migrate/20170413172724_create_item.rb
❯ rails g scenic:view items
      create  db/views/items_v01.sql
      create  db/migrate/20170413172735_create_items.rb
```

They're expected because in the latter case I specify that I want items, and we're not singularizing the view name ever. With that same config:

```
irb(main):001:0> "item".pluralize
=> "item"
irb(main):002:0> "items".pluralize
=> "items"
```
