### ISSUE TITLE
Schema dump ordering not respecting view dependencies

### ISSUE THREAD

**Issue by eidge** [thoughtbot/scenic#181]
Hi there guys.

Consider the case, where you have two views:

View A
View B

Where view B depends on view A. Sometimes the schema is dumped in way that view B will appear first then the view A. Effectively breaking schema loading.

I'll try to put up a test app in the weekend.

**Comment by devonestes** [comment]
@eidge Do you happen to have a short example of this behavior that you could share? I'd love to fix this, but I'm having a hard time recreating this behavior.

**Comment by skryl** [comment]
I'm seeing this as well. The views used to be added last to ```schema.rb```, now they are incorrectly added first before any of the tables are created. This happens every time a new ```schema.rb``` is written (every migration, etc).

**Comment by calebthompson** [comment]
Rails version?

**Comment by skryl** [comment]
Rails 5.0.0 / Scenic 1.3.0

**Comment by derekprior** [comment]
Any other schema extension type gems?

**Comment by Dorian** [comment]
@derekprior Maybe `schema_validations`.

It seems you are doing the right thing, I guess it's a conflict between Rails 5 [SchemaDumper](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/schema_dumper.rb)'s way and Scenic's [SchemaDumper](https://github.com/thoughtbot/scenic/blob/master/lib/scenic/schema_dumper.rb).

(I couldn't fix it when poking around)

**Comment by skryl** [comment]
@Dorian is correct, [schema_validations](https://github.com/SchemaPlus/schema_validations) was causing this, specifically https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/active_record/schema_dumper.rb#L43

**Comment by derekprior** [comment]
I can't think of anything we can do to prevent this. It's a side effect of there being no public API for schema extensions.

Anyone have any ideas?

**Comment by skryl** [comment]
Can't really do much about other libraries monkey patching ActiveRecord, going to close this.

**Comment by derekprior** [comment]
I think https://github.com/SchemaPlus/schema_plus_core/issues/18 is the right approach here. Closing.

**Comment by tmesquita** [comment]
https://github.com/SchemaPlus/schema_plus_core/pull/18 doesn't solve the problem. Due to the way SchemaPlus writes to the `db/schema.rb` file the view definitions will always be defined first. SchemaPlus doesn't write to the file stream until the last step in its [SchemaDumper#dump](https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/active_record/schema_dumper.rb#L18) method, also see [SchemaDump#assemble ](https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/schema_dump.rb#L23). 

Since `Scenic::SchemaDumper` is invoked first it'll write the view definitions to the schema file before SchemaPlus' SchemaDumper writes anything.

For anyone else looking for a fix.. I was able to get around this by writing a "plugin" that hooks into SchemaPlus' SchemaDumper. I also had to monkey patch Scenic's Schema dumper so that it does not write the views to the schema file (otherwise they are added twice).

**lib/scenic/schema_plus_plugin.rb**:
```
# inspired by https://github.com/SchemaPlus/schema_plus_views/blob/master/lib/schema_plus/views/middleware.rb
module Scenic
  module SchemaPlusPlugin
    module Middleware
      module Dumper
        module Tables
          def after(env)
            re_view_referent = %r{(?:(?i)FROM|JOIN) \S*\b(\S+)\b}
            env.connection.views.each do |view_name|
              next if env.dumper.ignored?(view_name)
              view = View.new(env: env, name: view_name)
              env.dump.tables[view.name] = view
              env.dump.depends(view.name, view.definition.scan(re_view_referent).flatten)
            end
          end

          class View
            attr_reader :name, :definition

            def initialize(env:, name:, definition: nil)
              @env = env
              @name = name
              @definition = definition || get_definition
            end

            def assemble(stream)
              heredelim = "SQL"
              stream.puts <<-ENDVIEW
  create_view "#{name}", sql_definition: <<-#{heredelim}
    #{definition}
  #{heredelim}

              ENDVIEW
            end

            private

            def get_definition
              result = @env.connection.execute("SELECT view_definition FROM information_schema.views WHERE table_schema = SCHEMA() AND table_name = #{@env.connection.quote(name)}")
              definition = result.first[0]

              definition.strip.gsub(/([\`]*#{@env.connection.current_database}[\`]*\.)/i, '')
            end
          end
        end
      end

      module Schema
        module DataSources
          module Mysql
            def after(env)
              DataSources.filter_out_views(env)
            end
          end

          def self.filter_out_views(env)
            env.sources -= env.connection.views
          end
        end
      end
    end
  end
end
```
**config/initializers/scenic.rb**:
```
# Monkey patch Scenic::SchemaDumper#tables to not write views to the schema file
# since they are being written via Scenic::SchemaPlusPlugin
module Scenic
  module SchemaDumper
    def tables(_)
      super
    end
  end
end

# Register the SchemaPlus plugin so that views are included in db/schema.rb after the tables they are dependent on
SchemaMonkey.register Scenic::SchemaPlusPlugin
```
