### ISSUE TITLE
Random order change of materialized views in Schema

### ISSUE THREAD

**Issue by prem-prakash** [thoughtbot/scenic#197]
Every time we run a migration to update or recreate a materialized view, all materialized views that already exist are randomly reordered (?) in the schema.

We are using rails 4.2.8 and scenic 1.3.0

Am I missing something? Or is this the expected behavior of gem?

**Comment by calebthompson** [comment]
Potentially related to https://github.com/thoughtbot/scenic/pull/191

**Comment by derekprior** [comment]
I do believe this is related to 191, but also could be due to differing postgres versions in use by members of the dev team. There's not much we can do about the latter if that is an issue, but the former is planned to be fixed in Scenic 2.0 (hopefully not far off)
