### ISSUE TITLE
Generate new view version without corresponding migration

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/scenic#203]
Consider a scenario where you are changing the name of a column on one of your base tables. That column is referenced in a view, so you need to drop the view, do the rename, and then update the view to the new version. My workflow for this typically goes:

1. Realize I want to change a name, so generate a migration. Write the `rename_column` method call. 

2. Run the migration and get an error because the column is referenced in a view.

3. Run `rails generate scenic:view my_view` to generate a new version of the view to update.

At this point, I tend to forget that the view generator also generated me a migration. So I manually write my `drop_view` and `create_view` statements in my original migration and then get confused when I get errors when I `rake db:migrate`. The errors are caused by this new migration that I have to manually delete.

Would a flag to the generator (`--no-migration`) make sense here?

**Comment by calebthompson** [comment]
Are you less likely to remember the new migration (which Git informs you of), or the `--no-migration` flag?

**Comment by derekprior** [comment]
I thought of that as I was writing this. Best response I could come up with was at least I could do `rails destroy scenic:view my_view` immediately followed by `--no-migration`.

But I can also use `:Rmigration` in vim, followed by `!rm %`.

**Comment by derekprior** [comment]
Even with that, I'd then be getting rid of all of my changes to the view. So forget this. It's a bad idea for my use case.
