### ISSUE TITLE
Issue with multiple database connections

### ISSUE THREAD

**Issue by ombr** [thoughtbot/scenic#209]
I would like to use scenic to create a view on another database connection.

Here is what I tried:

In my model:
```ruby
class Event < ApplicationRecord
  establish_connection :events_db
end
```
```ruby
class EventView < ApplicationRecord
  establish_connection :events_db
end
```

In my migration:

```ruby
EventStat.connection.create_view :event_stats, materialized: true
```

But is does not work, or it creates the view on the wrong database.

Any ideas how I could make it work ?

Thanks.

**Comment by nthj** [comment]
I think I might be missing something. In your example above, you reference `Event` and `EventView`, but your migration references `EventStat`. Does `EventStat` also have `establish_connection :events_db`, or should your migration look more like:

`Event.connection.create_view :event_stats, materialized: true`

**Comment by ombr** [comment]
Both `Event` and `EventStats` have `establish_connection :events_db`.
I am trying to create a view on another database for a table which is located on that other database.

In fact, `Event.connection` and `EventStat.connection` are the same connection to `events_db`.

Is that clear enough ?

**Comment by derekprior** [comment]
We default to using the `ActiveRecord::Base.connection` in the adapter. You could override this, but it's not really meant to be changed at runtime. I think it could work, though. See the docs here: https://github.com/thoughtbot/scenic/blob/master/lib/scenic/adapters/postgres.rb#L25-L40

**Comment by epetre** [comment]
So this gem doesn't support multiple databases from what I am gathering here. Would that be correct to assume?

**Comment by derekprior** [comment]
Not directly, though that's something we'd like to change.
