### ISSUE TITLE
Should update_view drop_view only if one exists?

### ISSUE THREAD

**Issue by olleolleolle** [thoughtbot/scenic#210]
`update_view` does two things: drop existing view matching the input name and then creating a new version.

Can the `drop_view` be "drop only if it exists"?

**Comment by derekprior** [comment]
This was done somewhat intentionally. The need to add `if exists` implies uncertainty about the current state of the schema, which shouldn't be the case. Do you have a use case where not having `if exists` is a great inconvenience?

**Comment by olleolleolle** [comment]
Thanks for spelling it out! It is strictly better.

**Comment by toomanyjoes** [comment]
Switching between feature branches with differing migrations and having to rollback and forward between the two is a use case for `if exists`
