### ISSUE TITLE
Does not seem to work with rails 5.1.3

### ISSUE THREAD

**Issue by funkytwig** [thoughtbot/scenic#219]
Installed gem:

$ gem install scenic
Successfully installed scenic-1.4.0
Parsing documentation for scenic-1.4.0
Done installing documentation for scenic after 0 seconds
1 gem installed

Tried using it:

$ rails generate scenic:view this_weeks_events
Running via Spring preloader in process 14389
Could not find generator 'scenic:view'. Maybe you meant 'controller', 'channel' or 'generator'
Run `rails generate --help` for more options.
Installed gem and did

$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ rails -v
Rails 5.1.3
$ gem list | grep scenic
scenic (1.4.0)
$

**Comment by louim** [comment]
You need to add the gem to your `gemfile` in your rails project, and install it with `bundle install`.

**Comment by funkytwig** [comment]
Thanks, as you may guess ime new to rails.  Love the idea behind the
gem, I did get views working but this looks much simpler. 

Ben 

On 06-09-2017 3:36 pm, Louis-Michel Couture wrote:

> You need to add the gem to your gemfile in your rails project, and install it with bundle install. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/thoughtbot/scenic/issues/219#issuecomment-327503826
[2]

**Comment by voraciousdev** [comment]
I also ran into this same error, but it was caused by Spring for me. `bin/spring stop` fixed the issue.
