### ISSUE TITLE
Ability to add RULES for view

### ISSUE THREAD

**Issue by schovi** [thoughtbot/scenic#220]
Hi,

I am currently working on project with some views and using this awesome gem. But I reach situation, where I completely switch from using default table to view.

```ruby
class Article < ActiveRecord
  self.table_name = :articles_with_computed_values
end
```

This works fine for getting values, but you can't insert, update or delete any record because of `cannot insert into view "articles_with_computed_values"`

This should be solved with RULE

```sql
CREATE RULE articles_with_computed_values_insert AS 
  ON INSERT TO articles_with_computed_values DO INSTEAD
    INSERT INTO articles VALUES (NEW.something, NEW.other, ...)
```

Do you think this is possible to be "automagically" solved with this gem? :)

**Comment by derekprior** [comment]
It's not something I would consider in scope here but there's [fx] which handles triggers and functions which may be in a better spot to handle this? Not sure.

[fx]: https://github.com/teoljungberg/fx

**Comment by derekprior** [comment]
cc @teoljungberg ?

**Comment by schovi** [comment]
@derekprior thanks for hint. Didnt know about that.

**Comment by seanfcarroll** [comment]
Might be useful but could possibly limit it to only if the view is over a single table.

**Comment by calebthompson** [comment]
Sorry, as Derek mentioned I don't think we're going to cover this.
