### ISSUE TITLE
MySQL adapter

### ISSUE THREAD

**Issue by cainlevy** [thoughtbot/scenic#221]
Howdy,

I've created a MySQL adapter with liberal inspiration from @pdebelak's scenic_sqlite_adapter. It's available at https://github.com/EmpaticoOrg/scenic-mysql_adapter.

Bonus: The MySQL adapter also supports reliable schema loading by dumping views in topographical order. (cf: #191)

**Comment by derekprior** [comment]
Thanks. I've added a link to the readme.
