### ISSUE TITLE
Views from PostGIS getting including in schema.rb

### ISSUE THREAD

**Issue by TylerRick** [thoughtbot/scenic#229]
Whereas #134 apparently fixed this for the case where postgis is installed into your app's main schema, it doesn't seem to have fixed it for when postgis is installed to its own schema (which I prefer to do for the same reason it's nice to keep vendor stuff in a `vendor/` directory).

`config/database.yml`:
```
  ...
  adapter: postgis
  postgis_schema:            postgis # default is public
  schema_search_path: public,postgis
```

This bug is made possible because a `postgis.` prefix *is* included in the list returned by `Scenic.database.views` but *not* included in the list added to `ignore_tables` by [activerecord-postgis-adapter](https://github.com/rgeo/activerecord-postgis-adapter/pull/208/files).

An easy non-forking workaround would be to just add this to an initializer:
```
ActiveRecord::SchemaDumper.ignore_tables += ["postgis.geography_columns", "postgis.geometry_columns", "postgis.raster_columns", "postgis.raster_overviews"]
```

But it seems like one of these gems should handle this configuration automatically.

So... Which one should be changed? Whose responsibility is it? :smile: 

It's not clear from http://guides.rubyonrails.org/configuring.html whether or not `ignore_tables` is expected to contain a `schema.` prefix (`ActiveRecord::SchemaDumper#remove_prefix_and_suffix` removes any table prefix like `foo_` but does nothing about `schema.` prefixes), but it seems to work to include it, so...

# Option 1: Fix in `activerecord-postgis-adapter`

One obvious place to put this would be in `activerecord-postgis-adapter` since it knows if it's using a different schema than the default and it could add the prefix there...

Couldn't just change `PostGIS.initial_setup` since it's called so early on...

```
[23, 32] in /home/tyler/code/ruby/geo/activerecord-postgis-adapter/activerecord-postgis-adapter/lib/active_record/connection_adapters/postgis_adapter.rb
   23: require "active_record/connection_adapters/postgis/setup"
   24: require "active_record/connection_adapters/postgis/oid/spatial"
   25: require "active_record/connection_adapters/postgis/create_connection"
   26: require "active_record/connection_adapters/postgis/postgis_database_tasks"
   27: 
=> 28: ActiveRecord::ConnectionAdapters::PostGIS.initial_setup
```

but could probably find a better callback point and move that code there...

# Option 2: Fix in `scenic`

It would be pretty easy to fix it in scenic too. Maybe something like:

```
    def dumpable_views_in_database
      @dumpable_views_in_database ||= Scenic.database.views.reject do |view|
        ignored?(view.name) or ignored?(view.name_without_schema)
      end
    end
```

Possible downside of that is that if you defined your own view, say, `geography_columns`, then it would be ignored. But that's already perhaps the expected behavior from https://github.com/rgeo/activerecord-postgis-adapter/pull/208 ...

Thoughts?

# Other code for reference

## Where `postgis.` prefix gets added by `scenic`

```
[21, 30] in /usr/local/bundle/gems/scenic-1.4.1/lib/scenic/schema_dumper.rb
   24:     def dumpable_views_in_database
   25:       byebug
=> 26:       @dumpable_views_in_database ||= Scenic.database.views.reject do |view|
   27:         ignored?(view.name)
   28:       end
   29:     end
(byebug) Scenic.database.views.map(&:name)
["postgis.geography_columns", "postgis.geometry_columns", "postgis.raster_columns", "postgis.raster_overviews", "users_search", ...]
```

```
[41, 50] in /usr/local/bundle/gems/scenic-1.4.1/lib/scenic/adapters/postgres/views.rb
   41: 
   42:         def to_scenic_view(result)
   43:           namespace, viewname = result.values_at "namespace", "viewname"
   44: 
   45:           if namespace != "public"
=> 46:             namespaced_viewname = "#{pg_identifier(namespace)}.#{pg_identifier(viewname)}"
   47:           else
   48:             namespaced_viewname = pg_identifier(viewname)
   49:           end
   50: 
(byebug) "#{pg_identifier(namespace)}.#{pg_identifier(viewname)}"
"postgis.geography_columns"
(byebug) method(__callee__)
#<Method: Scenic::Adapters::Postgres::Views#to_scenic_view>
```

**Comment by syntaxTerr0r** [comment]
Same issue here.

For the temporary workaround I also have this view: `postgis.spatial_ref_sys`

```ruby
ActiveRecord::SchemaDumper.ignore_tables += [
   'postgis.geography_columns',
   'postgis.geometry_columns',
   'postgis.spatial_ref_sys',
   'postgis.raster_columns',
   'postgis.raster_overviews'
]```

**Comment by derekprior** [comment]
I think @syntaxTerr0r's solution is sufficient for this from scenic's perspective.  As I understand the problem (which isn't fully), the fix for this should go in `activerecord-postgis-adapter`
