### ISSUE TITLE
Cascaded update for dependent materialized views in migration

### ISSUE THREAD

**Issue by Dirichi** [thoughtbot/scenic#235]
Thanks for this library, it's been very helpful! I would like that when I run a migration to update a materialized view on which other materialized views are dependent, these dependent views are dropped and then recreated. For example, say my schema is such that `team_usage` is a materialized view that depends on `daily_usage`, the migration below fails:

```ruby
  def change
    update_view :personal_usage, version: 2, revert_to_version: 1, materialized: true
  end
```

For now this works, but can get untidy with lots of dependencies:

```ruby
  def change
    drop_view :team_usage, materialized: true
    update_view :personal_usage, version: 2, revert_to_version: 1, materialized: true
    create_view :team_usage, materialized: true
  end
```
Thanks again

**Comment by devonestes** [comment]
Great minds think alike! I think this is a duplicate of my proposal for the same feature in the Scenic 2.0 RFC here: https://github.com/thoughtbot/scenic/issues/201#issuecomment-300863241

**Comment by Dirichi** [comment]
Ah, thanks a lot for this! Will close this one then 👍
