### ISSUE TITLE
Naming Convention for inflated Joins table?

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/scenic#244]
I'm using scenic to better handle views in Rails. In your use of Rails, have you run into a naming convention for joins tables that are inflated with views? (I'm asking here because [StackOverflow's](https://stackoverflow.com/questions/2878248/postgresql-naming-conventions?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) responses to style questions don't usually cover multiple technologies)

For a simple example, if my app has `Products` and `Quotes`, and I have a joins table of `QuotedProducts`, I'd love to just have a view represent that `QuotedProducts` table with commonly accessed columns filled in, so I don't have to fall back to Rails' `delegate` or denormalize the data.

[This views guide](http://www.postgresqltutorial.com/managing-postgresql-views/) uses the postfix _master or _info, which don't really scratch the itch I'm looking for.

Thanks!

**Comment by calebthompson** [comment]
You could use Rails' convention for many_to_many tables, which is to pluralize and alphabetize the table names:

`products_quotes`

Then you can use `quoted_products` as your view name.

Ultimately it's up to you what you want to call it. We haven't seen any conventions come up.
