### ISSUE TITLE
Feature suggestion: Ability to template views

### ISSUE THREAD

**Issue by joehorsnell** [thoughtbot/scenic#248]
Hi - thanks for your efforts in producing Scenic.

I'd like to ask if there's been any discussion around (or interest in) providing a mechanism for templating view definitions, eg using ERB, Mustache, etc.? Looking in the issues/PRs (including the v2 RFC #201) it appears not. FYI, we are using this approach [of templating views] on some of our projects at Bamboo and it works well, allowing for simple sharing of code, dynamic generation of lists of columns, etc.

The basic approach would be to detect a file extension (such as `db/views/my_view_v01.sql.erb`) for a view definition and run it through the appropriate template engine, which since it's a Rake task in your Rails app, would have access to any application code it needed to.

Is this something you'd be interested in getting a PR for?

Cheers, Joe.

**Comment by calebthompson** [comment]
Hi Joe.

The problem with that is that the SQL file needs to evaluate exactly the same up and down  for scheme migrations to be reversible, code changes such as adding or removing classes or modifying methods can cause migrations to fail, etc.

These issues come up in Ruby migrations already. An example is relying on an AR object in a migration safely means re-defining that class in case it’s removed later. I think we’d rather beer on the safe side and not include that.

It’s very possible and not too difficult to write a rake task on which db:migrate depends that would run ERB against db/views as you mention, so this is possible to roll in your own app. “Easy to do the right thing, possible to do other things” applies here.

Thanks!

**Comment by joehorsnell** [comment]
Hi @calebthompson - thanks for the quick response.

>These issues come up in Ruby migrations already. An example is relying on an AR object in a migration safely means re-defining that class in case it’s removed later.

Excellent point and yes, we are 100% familiar with that particular migrations subtlety, to the point that we generally use raw SQL in any migrations where DML is required, or use the 'migration-local AR model copy' trick you mentioned in some rare cases.

We are currently using our own (very simple) mechanism for running views in where we have a separate `db/views` directory (containing views/view templates) and the views are recreated where necessary _after_ migrations have run, so the 'consistent history' issue you mention is not a problem for us currently.

However, I like the more principled approach of using migrations to apply view changes and hadn't considered the point you raise.

How about an approach whereby the templating happens at development time (ie when you are running the Rails `generate scenic:view` task) and it results in the creation of a plain `.sql` text file containing the view definition?

Obviously this is something that could be handled (manually) outside of Scenic, but if a reliable and clearly-defined mechanism could be designed it might be a powerful addition to have?

Thoughts?

**Comment by joehorsnell** [comment]
Fair enough - thanks for the quick responses @calebthompson and @derekprior 👍
