### ISSUE TITLE
mysql support

### ISSUE THREAD

**Issue by westonplatter** [thoughtbot/scenic#70]
I'll make a pass at this unless someone has already written the code.

**Comment by derekprior** [comment]
This is definitely something we intended for the community to provide, though we expect that to be in the form of an adapter gem, `scenic-mysql`. 

We've found that the ability to plug and play adapters is important but that unless we are frequent users of those adapters, they tend to become buggy over time. That said, I'm interested to see how this goes and how the testing story would go (It'd be great to have a shared set of tests where/if appropriate).

**Comment by derekprior** [comment]
And to be fair, I could see `scenic-postgres` itself becoming a separate gem and you simply add the necessary adatper gem to your Gemfile to use `scenic`. We're just not stable enough to pursue that right now.

**Comment by calebthompson** [comment]
Agreed. At this point all you need to do is provide an adapter and override this line: https://github.com/thoughtbot/scenic/blob/fcfcdbb80560c49cbe415ba675b7fbc9cdef34cc/lib/scenic.rb#L18

**Comment by westonplatter** [comment]
I understand and agree with modulizing per db adapter, but similar to AR, I would suggest that modules should exist within the gem. What are the Pro/Cons you're looking at?

I'm looking at using scenic for a non-trivial production app that's on Rails 3.2.x, though we'll be upgrading soon. It's scenic or something else to manage a suite of coming views. 

I'm up for working through the kinks and putting in the effort to thoughtfully add to current conventions. Throwing half hearted code towards the project would be unkind on my part :)

**Comment by westonplatter** [comment]
He's a working set of `mysql2` changes.

https://github.com/westonplatter/scenic/commit/043212c43b71522a72ee0a4ed2675eeadf6c8fc0

I'll touch base again once I get testing figured out.

**Comment by derekprior** [comment]
It's not at all that the code would be of questionable quality and more a
concern over maintenance. When we make breaking changes to scenic we are,
perhaps, not best positioned to asses the impact on adapters we don't use
ourselves. When you move on to another project the code languishes and the
support burden shifts to us.

Additionally, there are versioning issues that arise. A breaking change to
the MySQL adapter would mean bumping the major scenic version, which means
everyone has to asses the appropriateness of that version - even those that
don't use that adapter.

I'm trying to keep an open mind but both @calebthompson and I have seen
this go poorly on our other projects.

**Comment by westonplatter** [comment]
Do you have a pattern for adapter-izing different dbs? I got mysql working within this repo, but wanted to push the MySQL logic into a separate gem/repo. If not, I'll hack something together.

**Comment by calebthompson** [comment]
As long as your gem defines a class Scenic::Adapters::Mysql which supports the same contract as https://github.com/thoughtbot/scenic/blob/master/lib/scenic/adapters/postgres.rb and overrides https://github.com/thoughtbot/scenic/blob/master/lib/scenic.rb#L17, it should work fine. That’s basically what we had in mind for adapters.

As far as testing, you can take a look at the Postgres adapter specs to get an idea. I'd also ensure that Scenic.database is what you expect and maybe have a high level test that just makes sure Mysql is actually being interacted with when you migrate.

**Comment by derekprior** [comment]
There now exists a configuration point for the adapter. See Scenic::Configuration.

**Comment by rennanoliveira** [comment]
If anyone falls on this issue, there are quite a few community made mysql adapters for scenic, the most downloaded one being [this one](https://github.com/startweaving/scenic_mysql).

Maybe it would be nice to add a section to the README with the community adapters, like omniauth has, so people get to know they exist.
I actually ended up making my own adapter as I did not know one had already been made :)

**Comment by MarkMurphy** [comment]
I second @rennanoliveira. The README for Scenic says it will link to any mysql adapters made available but hasn't done so.
https://github.com/thoughtbot/scenic/blob/master/README.md#faqs

**Comment by derekprior** [comment]
The Readme states that we're happy to review it and link to it, but no one
has submitted such a request. I do not want to send a bunch of MySQL users
to a project that is not actively maintained or doesn't want that
attention. My intention was that maintainers would request that they be
added.
