### ISSUE TITLE
NoMethodError for `create_view` in migrations

### ISSUE THREAD

**Issue by calebthompson** [thoughtbot/scenic#73]
Because Rails [no longer requires environment](https://github.com/rails/rails/commit/382a70c875c9378991c13874c43afd958a5d3809) for `db:schema:load`, Scenic isn't required and the load view methods aren't defined.

`rake environment db:schema:load` is a workaround for this, but isn't ideal.

**Comment by derekprior** [comment]
We could introduce this:

```ruby
Rake::Task["db:schema:load"].enhance [:environment]
```

which would have the effect of reverting the rails change...

**Comment by calebthompson** [comment]
Yeah, that's the easiest option. Other option is to throw together a `scenic:enviroment` task that loads Scenic and the dependencies it needs to load, which should be less than all of Rails.

On the off chance that someone is using both octopus and scenic, that could help prevent the original issue (which it seems the \*cough\*author of the offending change in Rails didn't fully understand).

**Comment by scashin133** [comment]
FYI this was reverted and is no longer an issue on the latest rails 4.2 version: https://github.com/rails/rails/pull/17920#issuecomment-96588202

**Comment by derekprior** [comment]
Sweet.
