### ISSUE TITLE
Document How Postgres can't infer a view's primary key

### ISSUE THREAD

**Issue by seanpdoyle** [thoughtbot/scenic#77]
```
@calebthompson: @derek We’re using Scenic. While inspecting with pg, the view has an `id` column, but `TheViewModel.first.id == nil` and `TheViewModel.find(1)` complains about not having a primary key

calebthompson [14:58] 
`self.primary_key = :id`

sean [14:58] 
Setting `self.primary_key = "id"` resolved the issue. Am I doing something wrong

calebthompson [14:58] 
Nope.

calebthompson [14:58]
Views can’t have primary keys in postgres.

calebthompson [14:58]
We could probably benefit from having that in the README.
```

**Comment by derekprior** [comment]
I dont think there's anything we can do about this at runtime unless we introduce a `Scenic::Model` module or base class which could inspect at runtime and make the proper `primary_key` call for you.

I'm leaning towards a documentation change to cover this as well. @calebthompson Would you also rule out a runtime fix?

**Comment by calebthompson** [comment]
I think this is to add a note to the README.

**Comment by calebthompson** [comment]
That was the result of the conversation that led to this issue.

**Comment by derekprior** [comment]
I'd like it to live in actual documentation as well - just not sure where. I'll poke around.
