### ISSUE TITLE
Support concurrent materialized view refreshes

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/scenic#92]
If you don't use `REFRESH MATERIALIZED VIEW CONCURRENTLY` then there's a chance your materialized view could be locked for selects while its refreshing. We can't just default to concurrent refreshes because in order to use `CONCURRENTLY` your materialized view has to have at least one unique index on a column. 

I dont think we should detect whether `CONCURRENTLY` can be used on a view - we should just accept an option and do as we're told.

See: http://www.postgresql.org/docs/9.4/static/sql-refreshmaterializedview.html

**Comment by devonestes** [comment]
@derekprior I've addressed this issue in #97 - hopefully it's along the lines of what you were thinking.

p.s. I really love The Bike Shed - it's probably my favorite technical podcast! Thanks for putting it out every week! :radio:

**Comment by derekprior** [comment]
Thanks @d
