### ISSUE TITLE
Create views in a different database schema

### ISSUE THREAD

**Issue by ianyamey** [thoughtbot/scenic#95]
Often, we create views in a different database schema, so that they are logically isolated from the `public` schema and can have a different set of access rules (eg `read_only` access granted to a `reporting` user).

Is there any way to define the schema name when using scenic?

**Comment by derekprior** [comment]
I believe that this should work fine, but there are a number of variables at play. Assuming the user you run migrations as has rights to the schema you want to write to, you should be able to do `create_view "my_schema.my_view"`. 

The generators don't like working with fully-qualified view names (with the ".") but everything else does work. This makes the process a little convoluted:

1. `rails generate scenic:view orders`
2. Edit the generated migration, which will say `create_view :orders` to say `create_view "my_schema.orders"`.
3. Rename the view definition file `db/views/orders_v01.sql` to `db/views/my_schema.orders_v01.sql`.

This seems to work. The process could be made smoother by updating the generators so they can accept a fully-qualified view name but are smart enough to  not try to use "CreateMySchema.Orders" as the migration class name or `MySchema.Orders` as the model name (with the model generator) but *do* use `"my_schema.orders"` as the string passed to `create_view` and `update_view`. I think this should be doable in a manner that isn't too ugly.

Give the manual process a shot and see if it will work for you. If it does and you want to take a stab at making it more generator friendly then I'd probably accept that PR so long as it can be done cleanly.

Let me know how it works out either way.

**Comment by derekprior** [comment]
@ianyamey Did this work for you? If so, any interest in attempting a patch? I don't think this is a popular enough use case for me to tackle right now, but as I said - if you're willing and the patch is not too obtrusive, I'd consider merging.
